### ISSUE TITLE
Geospatial Dashboard Development

### ISSUE THREAD

**Issue by laflamev** [Vancouver-Datajam/GIS-Interpolation#2]
## Tasks
- [x] Library Installation: Install necessary Python libraries, including plotly, to support the creation of interactive dashboards. You can do this using pip:
`pip install plotly dash pandas geopandas`
- [ ] Dashboard Layout Design: Plan and design the layout of the dashboard, including the arrangement of maps, charts, and filters.
- [ ] Data Integration: Integrate the Kriged climate surfaces and other relevant data into the dashboard for visualization.
- [ ] Interactive_ Elements: Implement interactive elements such as dropdown menus, sliders, and checkboxes to allow users to explore the data dynamically.
- [ ] Plotly Chart Creation: Use Plotly to create various types of charts (e.g., scatter plots, heatmaps) to visualize the climate data.
- [ ] Geospatial Mapping: Incorporate geospatial maps into the dashboard using Plotly's mapping capabilities to display the Kriged results.
- [ ] Data Filtering and Selection: Enable users to filter and select specific regions or timeframes within the dashboard to view targeted climate information.
- [ ] Dashboard Styling and Aesthetics: Customize the appearance of the dashboard, including colors, fonts, and overall design, for a polished and user-friendly interface.
- [ ] Testing and Debugging: Thoroughly test the dashboard functionality to ensure smooth interaction and address any potential issues.
- [ ] Documentation and User Guide: Provide clear documentation and user instructions for navigating and utilizing the interactive dashboard effectively.
- [ ] Integration with Kriging Results: Link the dashboard to the Kriged climate surfaces, allowing users to visualize both observed and interpolated climate data.

## Resources
- Dashboard example: https://viz.pmel.noaa.gov/osmc/?color_by=platform_type
- Article: https://medium.com/plotly/building-a-big-data-geographical-dashboard-with-open-source-tools-c5108d7d5683

## Step-By-Step Guide
Guide on creating a geospatial dashboard in Python using Plotly:
```python
# Step 4: Import necessary libraries
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import plotly.express as px
import geopandas as gpd

# Step 5: Create a Dash app
app = dash.Dash(__name__)

# Step 6: Load your geospatial data
gdf = gpd.read_file('path_to_your_shapefile.shp')

# Step 7: Define the layout of your dashboard
app.layout = html.Div([
    html.H1("Geospatial Dashboard"),
    
    # Dropdown for selecting a variable to visualize
    dcc.Dropdown(
        id='variable-dropdown',
        options=[
            {'label': column, 'value': column} for column in gdf.columns
        ],
        value=gdf.columns[0],  # Default selection
        multi=False
    ),
    
    # Geospatial map
    dcc.Graph(
        id='geo-map'
    )
])

# Step 8: Create callback function to update the map
@app.callback(
    Output('geo-map', 'figure'),
    Input('variable-dropdown', 'value')
)
def update_map(selected_variable):
    fig = px.choropleth(
        gdf,
        geojson=gdf.geometry,
        locations=gdf.index,
        color=selected_variable,
        projection="mercator"
    )
    
    fig.update_geos(fitbounds="locations", visible=False)
    fig.update_layout(
        title=f"{selected_variable} Distribution",
        coloraxis_showscale=True
    )
    
    return fig

# Step 9: Run the app
if __name__ == '__main__':
    app.run_server(debug=True)
```
Here's what each step does:
1. Import the necessary libraries, including Plotly, Dash, Pandas, and Geopandas.
2. Create a Dash app.
3. Load your geospatial data using Geopandas (replace 'path_to_your_shapefile.shp' with your actual file path).
4. Define the layout of your dashboard with HTML and Dash components.
5. Create a callback function to update the geospatial map based on user input (variable selection).
6. Run the app.
